apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark
spec:
  selector:
    matchLabels:
      app: spark-history-server
  replicas: 1
  template:
    metadata:
      name: spark-history-server
      labels:
        app: spark-history-server
    spec:
      volumes:
        - name: gcp-cred
          secret:
            secretName: google-cloud-key
      containers:
        - name: spark-history-server
          image: "damianfilonowicz/spark:v3.1.1-hadoop3-gcs-2.2.3-bq-0.22.2-guava-30.1.1-jre"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          volumeMounts:
            - name: gcp-cred
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: google-cloud-key
                  key: key.json
          command:
            - /opt/spark/bin/spark-class
            - -Dspark.hadoop.google.cloud.auth.service.account.enable=true
            - -Dspark.hadoop.google.cloud.auth.service.account.json.keyfile=/var/secrets/google/key.json
            - -Dspark.eventLog.enabled=true
            - -Dspark.eventLog.dir=gs://pyspark-demo-logs/
            - -Dspark.history.fs.logDirectory=gs://pyspark-demo-logs/
            - -Divy.cache.dir=/tmp
            - -Divy.home=/tmp
            - org.apache.spark.deploy.history.HistoryServer
          ports:
            - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-service
  namespace: spark
spec:
  selector:
    app: spark-history-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 18080
